version: 0.2

env:
  variables:
     AWS_DEFAULT_REGION: "us-east-2"
     IMAGE_REPO_NAME: "adiyodi_assignment3_ecr_public"
     AWS_ACCOUNT_ID: "211125509771"
     PUBLIC_ECR_REPO_URL: "public.ecr.aws"

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR Public...
      - AWS_PASSWORD=$(aws ecr-public get-login-password --region $AWS_DEFAULT_REGION)
      - echo $AWS_PASSWORD | docker login --username AWS --password-stdin $PUBLIC_ECR_REPO_URL

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $PUBLIC_ECR_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to public ECR...
      - docker push $PUBLIC_ECR_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"APP-PY","imageUri":"%s"}]' $CONTAINER_NAME $PUBLIC_ECR_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
