version: 0.2

env:
  variables:
     AWS_DEFAULT_REGION: "us-east-2"
     IMAGE_REPO_NAME: "adiyodi_assignment3_ecr_public"
     AWS_ACCOUNT_ID: "211125509771"

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i8q3x1g4  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t adiyodi_assignment3_ecr_public .
      - docker tag adiyodi_assignment3_ecr_public:latest public.ecr.aws/i8q3x1g4/adiyodi_assignment3_ecr_public:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/i8q3x1g4/adiyodi_assignment3_ecr_public:latest
      - printf '[{"name":"APP-PY","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
