# Build the container Image
steps:
  - name: 'docker-build-python-app'
    args: ['build', '-t', 'gcr.io/devops-lab-419615/adiyodi-assignment-3:$COMMIT_SHA', '.']

# Push the container Image
  - name: 'docker-push-python-app'
    args: ['push', 'gcr.io/devops-lab-419615/adiyodi-assignment-3:$COMMIT_SHA']

# Deploy the Docker container to Google Cloud Run
  - name: 'docker-deploy-to-cloud-run'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        gcloud run deploy python-app \
          --image=gcr.io/devops-lab-419615/adiyodi-assignment-3:$COMMIT_SHA \
          --platform=managed \
          --region=us-central1 \
          --port=5000 \
          --allow-unauthenticated

images:
  - 'gcr.io/devops-lab-419615/adiyodi-assignment-3:$COMMIT_SHA'
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
